version: '3.9'

services:
  db:
    container_name: postgres
    image: bitnami/postgresql:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRESQL_USERNAME: 'postgres'
      POSTGRESQL_PASSWORD: 'postgres'
      POSTGRESQL_DATABASE: 'postgres'
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: bitnami/redis:7.0
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  db-data:
  redis-data:
