// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets/actor/{id}": {
            "get": {
                "description": "Get actor by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets"
                ],
                "summary": "Get actor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Actor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.actor"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/assets/movie-genre/{id}": {
            "get": {
                "description": "Get movie genre by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets",
                    "Movie"
                ],
                "summary": "Get movie genre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Genre ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.genre"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/assets/movie-genres": {
            "get": {
                "description": "Get all movie genres",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets",
                    "Movie"
                ],
                "summary": "Get movie genres",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.genre"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/assets/network/{id}": {
            "get": {
                "description": "Get network by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets",
                    "TvShow"
                ],
                "summary": "Get network",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Network ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.studio"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/assets/studio/{id}": {
            "get": {
                "description": "Get studio by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets",
                    "Movie"
                ],
                "summary": "Get studio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Studio ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.studio"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/assets/tv-genre/{id}": {
            "get": {
                "description": "Get tv genre by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets",
                    "TvShow"
                ],
                "summary": "Get tv genre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Genre ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.genre"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/assets/tv-genres": {
            "get": {
                "description": "Get all tv genres",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Assets",
                    "TvShow"
                ],
                "summary": "Get tv genres",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.genre"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/calendar/movies": {
            "get": {
                "description": "Get movies calendar",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar",
                    "Movie"
                ],
                "summary": "Get movies calendar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Month",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.movieResults"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/calendar/movies/ical/{user-id}": {
            "get": {
                "description": "Get movies calendar in iCal format",
                "produces": [
                    "text/calendar"
                ],
                "tags": [
                    "Calendar",
                    "Movie"
                ],
                "summary": "Get movies calendar in iCal format",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "iCal data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/calendar/tvshows": {
            "get": {
                "description": "Get tv shows calendar",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar",
                    "TvShow"
                ],
                "summary": "Get tv shows calendar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Month",
                        "name": "month",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvReleasesResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/calendar/tvshows/ical/{user-id}": {
            "get": {
                "description": "Get tv shows calendar in iCal format",
                "produces": [
                    "text/calendar"
                ],
                "tags": [
                    "Calendar",
                    "TvShow"
                ],
                "summary": "Get tv shows calendar in iCal format",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "iCal data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/comment/media/{mediaID}": {
            "get": {
                "description": "Get media's comments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Get media's comments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "mediaID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.commentResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add comment to a media",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Add comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "mediaID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comment",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.commentRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.commentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/comment/user/{userID}": {
            "get": {
                "description": "Get user's comments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Get user's comments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.commentResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/comment/{commentID}": {
            "put": {
                "description": "Update comment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Update comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comment",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.commentRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User roles",
                        "name": "roles",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.commentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete comment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "Delete comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User roles",
                        "name": "roles",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "comment deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/media/comments": {
            "get": {
                "description": "Get medias ordered by number of comments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Media"
                ],
                "summary": "Get medias by comment",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/actor": {
            "get": {
                "description": "Get movies by actor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get movies by actor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Actor id",
                        "name": "actor",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/director": {
            "get": {
                "description": "Get movies by director",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get movies by director",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Director id",
                        "name": "director",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/genre": {
            "get": {
                "description": "Get movies by genre",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get movies by genre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Genre id",
                        "name": "genre",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/popular": {
            "get": {
                "description": "Get popular movies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get popular movies",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only available movies",
                        "name": "available",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResults"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/recent": {
            "get": {
                "description": "Get recent movies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get recent movies",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only available movies",
                        "name": "available",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.movieResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/recommendations/{movie}": {
            "get": {
                "description": "Get movie's recommendations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get movie's recommendations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Movie id",
                        "name": "movie",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.movieResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/search": {
            "get": {
                "description": "Search movies by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Search movies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only available movies",
                        "name": "available",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/movie/studio": {
            "get": {
                "description": "Get movies by studio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "Movie"
                ],
                "summary": "Get movies by studio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Studio id",
                        "name": "studio",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/actor": {
            "get": {
                "description": "Get tv shows by actor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Get tv shows by actor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Actor id",
                        "name": "actor",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/genre": {
            "get": {
                "description": "Get tv shows by genre",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Get tv shows by genre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Genre id",
                        "name": "genre",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/network": {
            "get": {
                "description": "Get tv shows by network",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Get tv shows by network",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Network id",
                        "name": "network",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/popular": {
            "get": {
                "description": "Get popular tv shows",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Get popular tv shows",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only available tv shows",
                        "name": "available",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResults"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/recent": {
            "get": {
                "description": "Get recent tv shows",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Get recent tv shows",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only available tv shows",
                        "name": "available",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.tvShowResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/recommendations/{tv}": {
            "get": {
                "description": "Get tv show's recommendations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Get tv show's recommendations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Show id",
                        "name": "show",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.tvShowResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/discover/tv/search": {
            "get": {
                "description": "Search tv shows by query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discover",
                    "TvShow"
                ],
                "summary": "Search tv shows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only available tv shows",
                        "name": "available",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media-file/file-tmdb/{id}": {
            "get": {
                "description": "Get media file info by its Media TMDB ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media File"
                ],
                "summary": "Get media file info by its Media TMDB ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.mediaFileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/base-tmdb/{id}": {
            "get": {
                "description": "Get media info by TMDB ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data"
                ],
                "summary": "Get media info",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.mediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/episode-tmdb/{id}": {
            "get": {
                "description": "Get TvShow Episode Metadata by TMDB ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "TvEpisode"
                ],
                "summary": "Get TvShow Episode Metadata by TMDB ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvEpisodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/movie-tmdb/{id}": {
            "get": {
                "description": "Get Movie Metadata by TMDB ID\nThe rating is from BingeMate, not from TMDB (only if available, else from TMDB)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "Movie"
                ],
                "summary": "Get Movie Metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/movie-tmdb/{id}/short": {
            "get": {
                "description": "Get Movie Short Metadata by TMDB ID\nThe rating is from BingeMate, not from TMDB (only if available, else from TMDB)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "Movie"
                ],
                "summary": "Get Movie Short Metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.movieResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/tvshow-episode-tmdb/{id}/{season}/{episode}": {
            "get": {
                "description": "Get TvShow Episode Metadata by TvShow TMDB ID, Season and Episode Number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "TvEpisode"
                ],
                "summary": "Get TvShow Episode Metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TvShow TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season Number",
                        "name": "season",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Episode Number",
                        "name": "episode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvEpisodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/tvshow-season-episodes-tmdb/{id}/{season}": {
            "get": {
                "description": "Get TvShow Season Episodes Metadata by TvShow TMDB ID and Season Number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "TvEpisode"
                ],
                "summary": "Get TvShow Season Episodes Metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TvShow TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season Number",
                        "name": "season",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.tvEpisodeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/tvshow-tmdb/{id}": {
            "get": {
                "description": "Get TvShow Metadata by TMDB ID\nThe rating is from BingeMate, not from TMDB (only if available, else from TMDB)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "TvShow"
                ],
                "summary": "Get TvShow Metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/media/tvshow-tmdb/{id}/short": {
            "get": {
                "description": "Get TvShow Short Metadata by TMDB ID\nThe rating is from BingeMate, not from TMDB (only if available, else from TMDB)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media Data",
                    "TvShow"
                ],
                "summary": "Get TvShow Short Metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.tvShowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rating/media/{mediaID}": {
            "get": {
                "description": "Get media's rating",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Get media's rating",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "mediaID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ratingResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Save media's rating",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Save media's rating",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "mediaID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Rating",
                        "name": "rating",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ratingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ratingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/rating/media/{mediaID}/own": {
            "get": {
                "description": "Get user's media rating",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Get user's media rating",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Media ID",
                        "name": "mediaID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user-id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ratingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        },
        "/rating/user/{userID}": {
            "get": {
                "description": "Get user's rating",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Get user's rating",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ratingResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.actor": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 3292
                },
                "name": {
                    "type": "string",
                    "example": "Nicholas Hoult"
                },
                "overview": {
                    "type": "string",
                    "example": "Nicholas Caradoc Hoult (born 7 December 1989) is an English actor. His body of work includes supporting work in big-budget mainstream productions and starring roles in independent projects in both the American and the British film industries. He has been nominated for awards such as a British Academy Film Award and a Critics Choice Award for his work."
                },
                "profileUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/rbyi6sOw0dGV3wJzKXDopm2h0NO.jpg"
                }
            }
        },
        "controllers.audioResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "example": "audio_1.m3u8"
                },
                "language": {
                    "type": "string",
                    "example": "jpn"
                }
            }
        },
        "controllers.commentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "This is a comment"
                }
            }
        },
        "controllers.commentResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "This is a comment"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                },
                "id": {
                    "type": "string",
                    "example": "eec1d6b7-97c9-47e9-846b-6817d0e3d4ed"
                },
                "mediaId": {
                    "type": "integer",
                    "example": 134564
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                },
                "userId": {
                    "type": "string",
                    "example": "eec1d6b7-97c9-47e9-846b-6817d0e3d4ed"
                }
            }
        },
        "controllers.commentResults": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.commentResponse"
                    }
                },
                "totalResult": {
                    "type": "integer",
                    "example": 1412
                }
            }
        },
        "controllers.crew": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 24310
                },
                "name": {
                    "type": "string",
                    "example": "Mitchell Amundsen"
                },
                "profileUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/zK4o3lfe6chC2qDHhxpuO1RJl2X.jpg"
                },
                "role": {
                    "type": "string",
                    "example": "Director"
                }
            }
        },
        "controllers.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "controllers.genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 35
                },
                "name": {
                    "type": "string",
                    "example": "Comédie"
                }
            }
        },
        "controllers.mediaFileResponse": {
            "type": "object",
            "properties": {
                "audios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.audioResponse"
                    }
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                },
                "duration": {
                    "type": "number",
                    "example": 1450.76
                },
                "filename": {
                    "type": "string",
                    "example": "index.m3u8"
                },
                "id": {
                    "type": "string",
                    "example": "eec1d6b7-97c9-47e9-846b-6817d0e3d4ed"
                },
                "subtitles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.subtitleResponse"
                    }
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                }
            }
        },
        "controllers.mediaResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                },
                "id": {
                    "type": "integer",
                    "example": 134564
                },
                "mediaType": {
                    "type": "string",
                    "example": "TvShow"
                },
                "name": {
                    "type": "string",
                    "example": "The Iceblade Sorcerer Shall Rule the World"
                },
                "releaseDate": {
                    "type": "string",
                    "example": "2023-01-06"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                }
            }
        },
        "controllers.movieResponse": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.person"
                    }
                },
                "backdropUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/e7FzphKs5gzoghDotAEp2FeP46u.jpg"
                },
                "crew": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.crew"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.genre"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 649609
                },
                "overview": {
                    "type": "string",
                    "example": "Le mal ne saurait survivre une éternité sans un petit coup de pouce.\r Dans cette version moderne du mythe de Dracula..."
                },
                "posterUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/lm3y4RNPu4aRDePsX5CkB9ndEdQ.jpg"
                },
                "present": {
                    "type": "boolean",
                    "example": true
                },
                "releaseDate": {
                    "type": "string",
                    "example": "2023-04-07"
                },
                "studios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.studio"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Renfield"
                },
                "voteAverage": {
                    "type": "number",
                    "example": 7.252
                },
                "voteCount": {
                    "type": "integer",
                    "example": 278
                }
            }
        },
        "controllers.movieResults": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.movieResponse"
                    }
                },
                "totalPage": {
                    "type": "integer",
                    "example": 71
                },
                "totalResult": {
                    "type": "integer",
                    "example": 1412
                }
            }
        },
        "controllers.person": {
            "type": "object",
            "properties": {
                "character": {
                    "type": "string",
                    "example": "R.M. Renfield"
                },
                "id": {
                    "type": "integer",
                    "example": 3292
                },
                "name": {
                    "type": "string",
                    "example": "Nicholas Hoult"
                },
                "profileUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/rbyi6sOw0dGV3wJzKXDopm2h0NO.jpg"
                }
            }
        },
        "controllers.ratingRequest": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "controllers.ratingResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                },
                "mediaId": {
                    "type": "integer",
                    "example": 134564
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-05-07T20:31:28.327382+02:00"
                },
                "userId": {
                    "type": "string",
                    "example": "eec1d6b7-97c9-47e9-846b-6817d0e3d4ed"
                }
            }
        },
        "controllers.ratingResults": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.ratingResponse"
                    }
                },
                "totalResult": {
                    "type": "integer",
                    "example": 14
                }
            }
        },
        "controllers.studio": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 33
                },
                "logoUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/8lvHyhjr8oUKOOy2dKXoALWKdp0.png"
                },
                "name": {
                    "type": "string",
                    "example": "Universal Pictures"
                }
            }
        },
        "controllers.subtitleResponse": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "example": "subtitle_1.vtt"
                },
                "language": {
                    "type": "string",
                    "example": "fre"
                }
            }
        },
        "controllers.tvEpisodeResponse": {
            "type": "object",
            "properties": {
                "airDate": {
                    "type": "string",
                    "example": "2023-03-24"
                },
                "episodeNumber": {
                    "type": "integer",
                    "example": 12
                },
                "id": {
                    "type": "integer",
                    "example": 4137463
                },
                "name": {
                    "type": "string",
                    "example": "Le plus puissant sorcier du monde révèle Akasha"
                },
                "overview": {
                    "type": "string",
                    "example": "Ray et ses amis volent au secours de Rebecca, qui montre des signes..."
                },
                "posterUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/uVqsuh8qrNX8tkQDpDF7nDZdg0w.jpg"
                },
                "present": {
                    "type": "boolean",
                    "example": true
                },
                "seasonNumber": {
                    "type": "integer",
                    "example": 1
                },
                "tvShowId": {
                    "type": "integer",
                    "example": 200777
                }
            }
        },
        "controllers.tvReleasesResults": {
            "type": "object",
            "properties": {
                "episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.tvEpisodeResponse"
                    }
                },
                "tvShows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.tvShowResponse"
                    }
                }
            }
        },
        "controllers.tvShowResponse": {
            "type": "object",
            "properties": {
                "actors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.person"
                    }
                },
                "backdropUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/oL459mgvcnc3jL90K7zkfvXQu0.jpg"
                },
                "crew": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.crew"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.genre"
                    }
                },
                "id": {
                    "type": "integer",
                    "example": 200777
                },
                "networks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.studio"
                    }
                },
                "nextEpisode": {
                    "$ref": "#/definitions/controllers.tvEpisodeResponse"
                },
                "overview": {
                    "type": "string",
                    "example": "Ray White est un jeune homme venant d'entrer dans la populaire académie de magie Arnold. En tant que..."
                },
                "posterUrl": {
                    "type": "string",
                    "example": "https://image.tmdb.org/t/p/original/aiJd0oGkBhf98uEH3F3yC7O48vr.jpg"
                },
                "present": {
                    "type": "boolean",
                    "example": true
                },
                "releaseDate": {
                    "type": "string",
                    "example": "2023-01-06"
                },
                "seasonsCount": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "Ended"
                },
                "title": {
                    "type": "string",
                    "example": "The Iceblade Sorcerer Shall Rule the World"
                },
                "voteAverage": {
                    "type": "number",
                    "example": 6.7
                },
                "voteCount": {
                    "type": "integer",
                    "example": 11
                }
            }
        },
        "controllers.tvShowResults": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.tvShowResponse"
                    }
                },
                "totalPage": {
                    "type": "integer",
                    "example": 71
                },
                "totalResult": {
                    "type": "integer",
                    "example": 1412
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Media Service API",
	Description:      "This is the API for the Media Service application\nThis help to give info about the media files and metadata\nThis also help to manage the media files for admins",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
