definitions:
  controllers.audioResponse:
    properties:
      bitrate:
        type: number
      codec:
        type: string
      language:
        type: string
    type: object
  controllers.errorResponse:
    properties:
      error:
        type: string
    type: object
  controllers.genre:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  controllers.mediaFileResponse:
    properties:
      audios:
        items:
          $ref: '#/definitions/controllers.audioResponse'
        type: array
      codec:
        type: string
      created_at:
        type: string
      duration:
        type: number
      filename:
        type: string
      id:
        type: string
      mime_type:
        type: string
      size:
        type: number
      subtitles:
        items:
          $ref: '#/definitions/controllers.subtitleResponse'
        type: array
      updated_at:
        type: string
    type: object
  controllers.mediaResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      media_type:
        type: string
      release_date:
        type: string
      tmdb_id:
        type: integer
      updated_at:
        type: string
    type: object
  controllers.movieResponse:
    properties:
      actors:
        items:
          $ref: '#/definitions/controllers.person'
        type: array
      backdrop_url:
        type: string
      crew:
        items:
          $ref: '#/definitions/controllers.person'
        type: array
      genres:
        items:
          $ref: '#/definitions/controllers.genre'
        type: array
      id:
        type: integer
      overview:
        type: string
      poster_url:
        type: string
      release_date:
        type: string
      studios:
        items:
          $ref: '#/definitions/controllers.studio'
        type: array
      title:
        type: string
      vote_average:
        type: number
      vote_count:
        type: integer
    type: object
  controllers.person:
    properties:
      character:
        type: string
      id:
        type: integer
      name:
        type: string
      profile_url:
        type: string
    type: object
  controllers.studio:
    properties:
      id:
        type: integer
      logo_url:
        type: string
      name:
        type: string
    type: object
  controllers.subtitleResponse:
    properties:
      code:
        type: string
      language:
        type: string
    type: object
info:
  contact: {}
  description: |-
    This is the API for the Media Service application
    This help to give info about the media files and metadata
    This also help to manage the media files for admins
  title: Media Service API
paths:
  /media-file/{id}:
    get:
      description: Get media file info by Media ID
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.mediaFileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get media file info
      tags:
      - Media Data
  /media/base-tmdb/{id}:
    get:
      description: Get media info by TMDB ID
      parameters:
      - description: TMDB ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.mediaResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get media info
      tags:
      - Media Data
  /media/base/{id}:
    get:
      description: Get media info by Media ID
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.mediaResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get media info
      tags:
      - Media Data
  /media/movie-tmdb/{id}:
    get:
      description: |-
        Get Movie Metadata by TMDB ID
        The rating is from BingeMate, not from TMDB (only if available, else from TMDB)
      parameters:
      - description: TMDB ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.movieResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get Movie Metadata
      tags:
      - Media Data
  /media/movie/{id}:
    get:
      description: |-
        Get Movie Metadata by media ID
        The rating is from BingeMate, not from TMDB (only if available, else from TMDB)
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.movieResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: Get Movie Metadata
      tags:
      - Media Data
swagger: "2.0"
